# Rules
$(LINUX_HEADERS_TARGET): $(ROOTFS_TARGET)
	make -C$(SOURCES_PATH)/$(LINUX_DIR) -j$(NB_THREADS) ARCH=$(ARCH) $(LINUX_DEFCONFIG)
	make -C$(SOURCES_PATH)/$(LINUX_DIR) -j$(NB_THREADS) ARCH=$(ARCH) INSTALL_HDR_PATH=$(ROOTFS_PATH) headers_install

$(LINUX_IMAGE_TARGET): $(LINUX_HEADERS_TARGET) $(BINUTILS_TARGET) $(CC_TARGET)
	make -C$(SOURCES_PATH)/$(LINUX_DIR) -j$(NB_THREADS) ARCH=$(ARCH) CROSS_COMPILE=$(TOOLS_PATH)/bin/$(TARGET)-
	make -C$(SOURCES_PATH)/$(LINUX_DIR) -j$(NB_THREADS) ARCH=$(ARCH) CROSS_COMPILE=$(TOOLS_PATH)/bin/$(TARGET)- uImage LOADADDR=$(LINUX_LOADADDR)

.PHONY: clean-linux
clean-linux:
	make -C$(SOURCES_PATH)/$(LINUX_DIR) mrproper

.PHONY: distclean-linux
distclean-linux:
	rm -rf $(SOURCES_PATH)/$(LINUX_DIR)
