# Packages list
PACKAGES += omap4-pvr-module
PACKAGES += omap4-pvr-libraries
PACKAGES += libpthread-stubs
PACKAGES += libgbm
PACKAGES += libdrm
PACKAGES += libjpeg
PACKAGES += wayland
PACKAGES += weston
PACKAGES += icu
PACKAGES += qt
PACKAGES += reflexio
